import numpy as np

# ANSWERS to the Questions in the file 04-Numpy Exercises.ipynb

print("\n-----EXERCISE-----\n")
print("1")
print(np.zeros(10))
print("\n")
print("2")
print(np.ones(10))
print("\n")
print("3")
# print(np.array(5).reshape(1, 10))
print("\n")
print("5")
print(np.arange(10, 51))
print("\n")
print("6")
print(np.arange(10, 51, 2))
print("\n")
print("7")
print(np.arange(0, 9).reshape(3, 3))
print("\n")
print("8")
print(np.eye(3, 3))
print("\n")
print("15")
print(np.random.rand(1))
print("\n")
print("33")
print(np.random.randn(25))
print("\n")
print("35")
print(np.arange(0.01, 1.01, 0.01))
print("\n")
print("36")
print(np.linspace(0, 1, 20))
print("\n")
print("40")
print(np.array([[12, 13, 14, 15], [17, 18, 19, 20], [22, 23, 24, 25]]))
print("41")
print(np.random.randint(20, 21))
print("\n")
print("42")
print(np.array([2, 7, 12]).reshape(3, 1))
print("\n")
print("44")
print(np.arange(21, 26, 1))
print("\n")
print("49")
print(np.arange(16, 26).reshape(2, 5))
print("\n")
print("50")
mat = np.arange(1, 26).reshape(5, 5)
print(mat)
print(np.sum(mat))
print("\n")
print("51")
print(np.std(mat))
print("\n")
print("53")
print(np.sum(mat, 1).reshape(5, 1))  # Sum of all elements in a row
print("\n")
print(np.sum(mat, 0))  # Sum of all elements in a column
